### ISSUE TITLE
The time of updating code

### ISSUE THREAD

**Issue by Yassin-fan** [Scarecrow0/SGTR#1]
Thanks for your work about end-to-end SGG, it is interesting and inspiring!
I'd like to learn about more details about the work during running the code, and it would be wonderful if there is a clear time point of updating the code.
Thanks again for your work.

**Comment by Scarecrow0** [comment]
Hi ! 
Thanks for paying attention on our work.
We will release the code after the main conference of CVPR 2022
stay tuned !
