### ISSUE TITLE
Training with multi GPUs

### ISSUE THREAD

**Issue by Bartopt** [Scarecrow0/SGTR#14]
The code runs normally when training on a single GPU (**pods_train --num-gpus 1**)
However, it returns errors when training on multi GPUs (**pods_train --num-gpus 2**)
The log is as follows:

> Scan GPUs to get 2 free GPU ([0, 1])
> soft link to /data/Program/SGTR-main/outputs//playground/sgg/detr.res101.c5.one_stage_rel_tfmer
> Command Line Args: Namespace(disable_gpu_check=False, dist_url='tcp://127.0.0.1:49192', eval_only=False, machine_rank=0, num_gpus=2, num_machines=1, opts=[], resume=False, skip_git_commit=False)
> Traceback (most recent call last):
>   File "/data/Program/SGTR-main/tools/train_net.py", line 295, in <module>
>     args=(args,),
>   File "/data/Program/SGTR-main/cvpods/engine/launch.py", line 80, in launch
>     daemon=False,
>   File "/opt/conda/lib/python3.7/site-packages/torch/multiprocessing/spawn.py", line 230, in spawn
>     return start_processes(fn, args, nprocs, join, daemon, start_method='spawn')
>   File "/opt/conda/lib/python3.7/site-packages/torch/multiprocessing/spawn.py", line 188, in start_processes
>     while not context.join():
>   File "/opt/conda/lib/python3.7/site-packages/torch/multiprocessing/spawn.py", line 150, in join
>     raise ProcessRaisedException(msg, error_index, failed_process.pid)
> torch.multiprocessing.spawn.ProcessRaisedException: 
> 
> -- Process 0 terminated with the following error:
> Traceback (most recent call last):
>   File "/opt/conda/lib/python3.7/site-packages/torch/multiprocessing/spawn.py", line 59, in _wrap
>     fn(i, *args)
>   File "/data/Program/SGTR-main/cvpods/engine/launch.py", line 101, in _distributed_worker
>     comm.synchronize()
>   File "/data/Program/SGTR-main/cvpods/utils/distributed/comm.py", line 94, in synchronize
>     dist.barrier()
>   File "/opt/conda/lib/python3.7/site-packages/torch/distributed/distributed_c10d.py", line 2709, in barrier
>     work = default_pg.barrier(opts=opts)
> RuntimeError: NCCL error in: ../torch/csrc/distributed/c10d/ProcessGroupNCCL.cpp:891, internal error, NCCL version 21.0.3
> ncclInternalError: Internal check failed. This is either a bug in NCCL or due to memory corruption

Do the author have any suggestions about this problem?

**Comment by Bartopt** [comment]
I set GLOO_SOCKET_IFNAME=eth0, NCCL_SOCKET_IFNAME=eth0 in ~/.bashrc and change the value of ip at https://github.com/Scarecrow0/SGTR/blob/03bdd6554f12d521807cf95fe6a7daa7d3bb01dc/cvpods/engine/launch.py#L22
The code successfully runs on our multi GPUs cluster.

**Comment by Scarecrow0** [comment]
It may occur error if your don't have ib network in your computation cluster.
Directly use the 127.0.0.1 is also ok for the single machine with multi GPU, refer to init codebase of cvpods.
https://github.com/Megvii-BaseDetection/cvpods/blob/2deea5dc659371318c8a570c644201d913a83027/cvpods/engine/launch.py#L33
