### ISSUE TITLE
Training time on the datasets

### ISSUE THREAD

**Issue by daoyuan98** [Scarecrow0/SGTR#5]
Hi authors, 

Thank you so much for the great work!

May I know how long does it take to train your model on Visual Genome and OpenImages with 4 GPUs? 

Thanks you!

**Comment by Scarecrow0** [comment]
Hi, 
Thanks for interest in our work at SGTR.
It takes about 100k terations for best performance. You can refer to the training log included in our provided checkpoint.

**Comment by daoyuan98** [comment]
Got it! Thank you so much for your reply!
