### ISSUE TITLE
Change to SGCls and PredCls

### ISSUE THREAD

**Issue by bicheng-xu** [Scarecrow0/SGTR#7]
Hi,

On the Visual Genome Dataset, I see that the current code will be trained in the SGDet (Scene Graph Detection) setting by default. I am wondering where I can make changes to train the model in the SGCls (Scene Graph Classification) setting and/or PredCls (Predicate Classification) setting? I am assuming that somewhere in some config file should set some related flags, but I can not find them...

Thanks!

**Comment by Scarecrow0** [comment]
Hi,

Since we use the DETR as a detector, the ROI align is not supported naturally.
For mimic SGCls or PredCls, you may add the extra ROI align in the model. However, it may break the architecture of SGTR and lead to sub-optimal performance.

Good luck!
